<?php

$this->getPluginBag()->appendStylesheets(array(
    'https://bootswatch.com/4/cosmo/bootstrap.min.css',
    '@Payment/site-styles.css'
))
->load(array('jquery', 'site'));

?>
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <meta name="csrf-token" content="<?= $csrfToken; ?>" />

    <title><?php $this->show($title); ?></title>

    <?php foreach ($this->getPluginBag()->getStylesheets() as $src): ?>
    <link rel="stylesheet" href="<?= $src; ?>" />
    <?php endforeach; ?>

</head>
<body>

<section class="main">
    <div class="container">
        <div class="main-wrapper">
            <?= $fragment; ?>
        </div>
    </div>
</section>

<?php foreach ($this->getPluginBag()->getScripts() as $src): ?>
<script src="<?= $src; ?>"></script>
<?php endforeach; ?>

</body>
</html>