<?php

$this->getPluginBag()->appendStylesheets([
    'https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css',
    '@Payment/site-styles.css'
])
->load(['jquery', 'site']);

?>
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <meta name="csrf-token" content="<?= $csrfToken; ?>" />

    <title><?= $this->translate(isset($title) ? $title : 'Payment processing'); ?></title>

    <?php foreach ($this->getPluginBag()->getStylesheets() as $src): ?>
    <link rel="stylesheet" href="<?= $src; ?>" />
    <?php endforeach; ?>

</head>
<body>

<section class="main">
    <div class="container">
        <div class="main-wrapper">
            <?= $fragment; ?>
        </div>
    </div>
</section>

<?php foreach ($this->getPluginBag()->getScripts() as $src): ?>
<script src="<?= $src; ?>"></script>
<?php endforeach; ?>

</body>
</html>