<?php

use Krystal\Form\Element;

?>

<h2 class="page-header"><?php $this->show($title); ?></h2>
<br />

<form class="form-horizontal" autocomplete="off" method="POST">
  <?= Element::hidden('id', $entity['id']); ?>
  <?= Element::hidden('amount', $entity['amount']); ?>
  <?= Element::hidden('currency', $entity['currency']); ?>
  <?= Element::hidden('module', $entity['module']); ?>
  <?= Element::hidden('extension', $entity['extension']); ?>

  <fieldset>
    <div class="form-group">
      <label for="inputName" class="col-lg-2 control-label"><?php $this->show('Your name'); ?></label>
      <div class="col-lg-10">
        <?= Element::text('payer', $entity['payer'], ['class' => 'form-control', 'id' => 'inputName', 'placeholder' => $this->translate('Type your name')]); ?>
      </div>
    </div>

    <div class="form-group">
      <label for="inputPs" class="col-lg-12 control-label"><?php $this->show('Payment System'); ?></label>
      <div class="col-lg-10">
        <?= Element::select('extension', $this->translateArray($extensions), $entity['extension'], array('class' => 'form-control', 'id' => 'inputPs')); ?>
      </div>
    </div>

    <div class="form-group">
      <label for="inputModule" class="col-lg-12 control-label"><?php $this->show('Module'); ?></label>
      <div class="col-lg-10">
        <?= Element::select('module', $this->translateArray($modules), $entity['module'], array('class' => 'form-control', 'id' => 'inputModule')); ?>
      </div>
    </div>

    <div class="form-group">
      <label for="inputProduct" class="col-lg-12 control-label"><?php $this->show('Product'); ?></label>
      <div class="col-lg-10">
        <?= Element::textarea('product', $entity['product'], ['class' => 'form-control', 'id' => 'inputProduct', 'placeholder' => $this->translate('Product name')]); ?>
      </div>
    </div>

    <?php if ($entity['amount'] !== false): ?>
    <div class="form-group">
      <label for="inputAmount" class="col-lg-2 control-label"><?php $this->show('Amount'); ?></label>
      <div class="col-lg-10">
        <?= Element::number('amount', $entity['amount'], ['class' => 'form-control', 'min' => 1, 'id' => 'inputAmount', 'placeholder' => $this->translate('Amount to be charged')]); ?>
      </div>
    </div>
    <?php endif; ?>

    <div class="form-group">
      <div class="col-lg-10 pull-right">
        <button type="submit" data-button="submit" class="btn btn-success"><?php $this->show('Submit'); ?></button>
      </div>
    </div>
  </fieldset>
</form>
