<?php

use Krystal\Form\Element;

?>

<h2 class="page-header mb-3"><?= $this->translate($title); ?></h2>

<form class="row g-3" autocomplete="off" method="POST">
  <?= Element::hidden('id', $entity['id']); ?>
  <?= Element::hidden('amount', $entity['amount']); ?>
  <?= Element::hidden('currency', $entity['currency']); ?>
  <?= Element::hidden('module', $entity['module']); ?>
  <?= Element::hidden('extension', $entity['extension']); ?>

  <fieldset>
    <div class="mb-3 row">
      <label for="inputName" class="col-lg-2 col-form-label"><?= $this->translate('Your name'); ?></label>
      <div class="col-lg-10">
        <?= Element::text('payer', $entity['payer'], ['class' => 'form-control', 'id' => 'inputName', 'placeholder' => $this->translate('Type your name')]); ?>
      </div>
    </div>

    <div class="mb-3 row">
      <label for="inputEmail" class="col-lg-2 col-form-label"><?= $this->translate('Your email'); ?></label>
      <div class="col-lg-10">
        <?= Element::email('email', $entity['email'], ['class' => 'form-control', 'id' => 'inputEmail', 'placeholder' => $this->translate('Type your email for getting notifications')]); ?>
      </div>
    </div>

    <div class="mb-3 row">
      <label for="inputPs" class="col-lg-12 col-form-label"><?= $this->translate('Payment System'); ?></label>
      <div class="col-lg-10">
        <?= Element::select('extension', $this->translateArray($extensions), $entity['extension'], ['class' => 'form-select', 'id' => 'inputPs']); ?>
      </div>
    </div>

    <div class="mb-3 row">
      <label for="inputModule" class="col-lg-12 col-form-label"><?= $this->translate('Module'); ?></label>
      <div class="col-lg-10">
        <?= Element::select('module', $this->translateArray($modules), $entity['module'], ['class' => 'form-select', 'id' => 'inputModule']); ?>
      </div>
    </div>

    <div class="mb-3 row">
      <label for="inputProduct" class="col-lg-12 col-form-label"><?= $this->translate('Product'); ?></label>
      <div class="col-lg-10">
        <?= Element::textarea('product', $entity['product'], ['class' => 'form-control', 'id' => 'inputProduct', 'placeholder' => $this->translate('Product name')]); ?>
      </div>
    </div>

    <?php if ($entity['amount'] !== false): ?>
    <div class="mb-3 row">
      <label for="inputAmount" class="col-lg-2 col-form-label"><?= $this->translate('Amount'); ?></label>
      <div class="col-lg-10">
        <?= Element::number('amount', $entity['amount'], ['class' => 'form-control', 'min' => 1, 'id' => 'inputAmount', 'placeholder' => $this->translate('Amount to be charged')]); ?>
      </div>
    </div>
    <?php endif; ?>

    <div class="mb-3 row">
      <div class="col-lg-10 float-end">
        <button type="submit" data-button="submit" class="btn btn-success"><?= $this->translate('Submit'); ?></button>
      </div>
    </div>
  </fieldset>
</form>