<!DOCTYPE html>
<html>
<head>
    <title><?php $this->show('Processing your request... Please wait'); ?></title>
</head>
<body>
    <form method="<?= $gateway->getMethod(); ?>" action="<?= $gateway->getAction(); ?>">
        <?= $gateway->renderFields(); ?>
    </form>

    <script>
        // Get current form element
        var form = document.getElementsByTagName('form');

        // And submit immediately
        form[0].submit();
    </script>
</body>
</html>