<?php

/**
 * This template render after payment is processed.
 * You can use $code variable to determine what happened
 */

use Payment\Collection\ResponseCodeCollection;

?>

<div class="mt-5">
    <?php if ($code == ResponseCodeCollection::RESPONSE_SUCCESS): ?>
    <h3 class="mb-3"><?php $this->show('Thank you!'); ?></h3>
    <p><?php $this->show('You have successfully confirmed your payment.'); ?></p>
    <?php endif; ?>

    <?php if ($code == ResponseCodeCollection::RESPONSE_CANCEL): ?>
    <h3 class="mb-3"><?php $this->show('Payment cancellation'); ?></h3>
    <p><?php $this->show('You canceled payment or internal error occurred'); ?></p>
    <?php endif; ?>

    <?php if ($code == ResponseCodeCollection::RESPONSE_DUPLICATE): ?>
    <h3 class="mb-3"><?php $this->show('Error'); ?></h3>
    <p><?php $this->show('This transaction has already been processed'); ?></p>

    <?php endif; ?>
    
    <p><a class="text-muted" href="/"><?php $this->show('Go home'); ?></a></p>
</div>