<?php

use Krystal\Form\Element;

?>

<form class="card" autocomplete="off">
    <div class="card-body">
        <?= Element::hidden('transaction[id]', $transaction->getId()); ?>

        <div class="mb-3">
            <label class="form-label"><?= $this->translate('Payer'); ?></label>
            <?= Element::text('transaction[payer]', $transaction->getPayer(), ['class' => 'form-control']); ?>
        </div>

        <div class="mb-3">
            <label class="form-label"><?= $this->translate('Email'); ?></label>
            <?= Element::email('transaction[email]', $transaction->getEmail(), ['class' => 'form-control']); ?>
        </div>

        <div class="row">
            <div class="col-3">
                <div class="mb-3">
                    <label class="form-label"><?= $this->translate('Amount'); ?></label>
                    <?= Element::text('transaction[amount]', $transaction->getAmount(), ['class' => 'form-control']); ?>
                </div>
            </div>
            
            <div class="col-3">
                <div class="mb-3">
                    <label class="form-label"><?= $this->translate('Currency'); ?></label>
                    <?= Element::text('transaction[currency]', $transaction->getCurrency(), ['class' => 'form-control']); ?>
                </div>
            </div>

            <div class="col-3">
                <div class="mb-3">
                    <label class="form-label"><?= $this->translate('Payment System'); ?></label>
                    <?= Element::select('transaction[extension]', $this->translateArray($extensions), $transaction->getExtension(), ['class' => 'form-select']); ?>
                </div>
            </div>
        </div>

        <div class="mb-3">
            <label class="form-label"><?= $this->translate('Status'); ?></label>
            <?= Element::select('transaction[status]', $this->translateArray($statuses), $transaction->getStatus(), ['class' => 'form-select']); ?>
        </div>

        <div class="mb-3">
            <label class="form-label"><?= $this->translate('Date and time'); ?></label>
            <?= Element::text('transaction[datetime]', $transaction->getDatetime(), ['class' => 'form-control']); ?>
        </div>

        <div class="mb-3">
            <label class="form-label"><?= $this->translate('Module'); ?></label>
            <?= Element::select('transaction[module]', $this->translateArray($modules), $transaction->getModule(), ['class' => 'form-select']); ?>
        </div>

        <div class="mb-3">
            <label class="form-label"><?= $this->translate('Description'); ?></label>
            <?= Element::textarea('transaction[description]', $transaction->getDescription(), ['class' => 'form-control']); ?>
        </div>

        <?php $this->loadPartial('actions', [
            'new' => !$transaction->getId(),
            'add' => 'Payment:Admin:Transaction@addAction',
            'edit' => 'Payment:Admin:Transaction@editAction',
            'save' => 'Payment:Admin:Transaction@saveAction',
            'cancel' => 'Payment:Admin:Transaction@indexAction'
        ]); ?>
    </div>
</form>