<?php

use Krystal\Form\Element;
defined('KRYSTAL') or die;

?>

<form class="card" data-group="transaction" autocomplete="off">
    <?= Element::hidden('transaction[id]', $transaction->getId()); ?>

    <div class="form-group">
        <label class="col-lg-12"><?php $this->show('Payer'); ?></label>
        <div class="col-lg-10">
            <?= Element::text('transaction[payer]', $transaction->getPayer(), array('class' => 'form-control')); ?>
        </div>
    </div>

    <div class="form-group">
        <label class="col-lg-12"><?php $this->show('Email'); ?></label>
        <div class="col-lg-10">
            <?= Element::email('transaction[email]', $transaction->getEmail(), array('class' => 'form-control')); ?>
        </div>
    </div>

    <div class="row">
        <div class="col-3">
            <div class="form-group">
                <label class="col-lg-12"><?php $this->show('Amount'); ?></label>
                <div class="col-lg-12">
                    <?= Element::text('transaction[amount]', $transaction->getAmount(), array('class' => 'form-control')); ?>
                </div>
            </div>
        </div>
        
        <div class="col-3">
            <div class="form-group">
                <label class="col-lg-12"><?php $this->show('Currency'); ?></label>
                <div class="col-lg-12">
                    <?= Element::text('transaction[currency]', $transaction->getCurrency(), array('class' => 'form-control')); ?>
                </div>
            </div>
        </div>

        <div class="col-3">
            <div class="form-group">
                <label class="col-lg-12"><?php $this->show('Payment System'); ?></label>
                <div class="col-lg-12">
                    <?= Element::select('transaction[extension]', $this->translateArray($extensions), $transaction->getExtension(), array('class' => 'form-control')); ?>
                </div>
            </div>
        </div>
    </div>

    <div class="form-group">
        <label class="col-lg-12"><?php $this->show('Status'); ?></label>
        <div class="col-lg-10">
            <?= Element::select('transaction[status]', $this->translateArray($statuses), $transaction->getStatus(), array('class' => 'form-control')); ?>
        </div>
    </div>

    <div class="form-group">
        <label class="col-lg-12"><?php $this->show('Date and time'); ?></label>
        <div class="col-lg-10">
            <?= Element::text('transaction[datetime]', $transaction->getDatetime(), array('class' => 'form-control')); ?>
        </div>
    </div>

    <div class="form-group">
        <label class="col-lg-12"><?php $this->show('Module'); ?></label>
        <div class="col-lg-10">
            <?= Element::select('transaction[module]', $this->translateArray($modules), $transaction->getModule(), array('class' => 'form-control')); ?>
        </div>
    </div>

    <div class="form-group">
        <label class="col-lg-12"><?php $this->show('Description'); ?></label>
        <div class="col-lg-10">
            <?= Element::textarea('transaction[description]', $transaction->getDescription(), array('class' => 'form-control')); ?>
        </div>
    </div>

    <?php $this->loadPartial('actions', array(
        'new' => !$transaction->getId(),
        'add' => 'Payment:Admin:Transaction@addAction',
        'edit' => 'Payment:Admin:Transaction@editAction',
        'save' => 'Payment:Admin:Transaction@saveAction',
        'cancel' => 'Payment:Admin:Transaction@indexAction'
    )); ?>

</form>
